Criar um Array NumPy com 10 elementos inteiros aleatórios no invervalo [0,100] e exiba os valores  e o tipo de dado do array

In [ ]:
import numpy as np

array_numpy = np.random.randint(0,100,size=10)
print(array_numpy)
print(array_numpy.dtype)


Crie uma matriz 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.

In [41]:
matriz = np.random.rand(5,5)

print("Min:",matriz.min())
print("Max:",matriz.max())
print("Med:",matriz.mean())


Min: 0.06723601504059229
Max: 0.9883463695056076
Med: 0.5028198751999087


Crie um array com 10 elementos aleatórios no intervalo [0,1]. Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.

In [42]:
first_array = np.random.rand(10)
print(first_array)

second_array = (first_array*10).astype(int)
print(second_array)

[0.93455253 0.14344964 0.12575736 0.27223108 0.76791293 0.9636488
 0.95613153 0.802342   0.32249172 0.49410896]
[9 1 1 2 7 9 9 8 3 4]


Crie um array de duas dimensões com shape (3,3) e valores aleatórios inteiros no intervalo [0,9]. Substitua todos os elementos da segunda linha por -1.

In [55]:
import pandas as pd
td = np.random.randint(0,10, (3,3))
td[1,:] = -1
print(td)


[[ 1  5  2]
 [-1 -1 -1]
 [ 7  2  4]]


Crie um dataframe com as seguintes informações:
    Coluna "fruta": "Banana", "Maça", "Pera"
    Coluna "preco":7.90,10.20,11.80
    Coluna "quantidade":12,3,4

In [59]:
arr = np.array([["Banana",7.90,12],["Maça",10.20,3],["Pera",11.80,4]])
df = pd.DataFrame(arr,columns=['fruta','preco','quantidade'])
print(df)


    fruta preco quantidade
0  Banana   7.9         12
1    Maça  10.2          3
2    Pera  11.8          4
